--- Create user table ---
create type user_role as enum ('Admin', 'Customer')
create table users (
  user_id bigint generated by default as identity primary key,
  name varchar(50) not null,
  email varchar(60) unique not null,
  password varchar(80) not null,
  phone varchar(15) not null,
  role user_role
)

--- Create vehicles table
create type vehicle_status as enum ('available', 'rented', 'maintenance')
create type vehicle_type as enum ('car','bike','truck')
create table vehicles (
  vehicle_id bigint generated by default as identity primary key,
  name varchar(70) not null,
  type vehicle_type,
  registration_number varchar(50) unique not null,
  price int not null,
  status vehicle_status
)

--- Create booking
create type booking_status as enum ('pending','confirmed','completed','cancelled')
create table bookings(
  booking_id bigint generated by default as identity primary key,
  user_id bigint references users(user_id) not null,
  vehicle_id bigint references vehicles(vehicle_id) not null,
  start_date date not null,
  end_date date not null,
  status booking_status,
  total_cost int not null
)


-- query 1
select b.booking_id,u.name as customer_name, v.name as vehicle_name, b.start_date, b.end_date, b.status from bookings b
  inner join users u on b.user_id = u.user_id
  inner join vehicles v on b.vehicle_id = v.vehicle_id

-- query 2
select * from vehicles where not exists (
  select vehicle_id from bookings where bookings.vehicle_id = vehicles.vehicle_id
)

-- query 3
select * from vehicles where vehicles.type = 'car'

--query 4

select v.name, count(b.vehicle_id) from vehicles v
  join bookings b on b.vehicle_id = v.vehicle_id
    group by v.vehicle_id having count(v.vehicle_id) > 1